### ISSUE TITLE
US Gov attempts failing using adf version @2

### ISSUE THREAD

**Issue by Sean-Steefel** [liprec/vsts-publish-adf#85] opened 2022-04-27 21:33 UTC
Greetings author,

we are calling the task as so (service connection is GCC connection)
`- task: toggle-adf-trigger@2`
`  displayName: 'Stop trigger(s) in DataFactory fdo-adf-${{ parameters.adfName}}-${{ parameters.environmentCode}}'`
`  inputs:`
`    azureSubscription: '${{ parameters.azureSpnName }}'`
`    ResourceGroupName: 'fdo-rg-etl-${{ parameters.environmentCode}}'`
`    DatafactoryName: 'fdo-adf-${{ parameters.adfName}}-${{ parameters.environmentCode}}'`
`    TriggerFilter: '*'`
`    TriggerStatus: 'stop' # Options: start, stop`

Evidence showing service connection working (ADO using Az CLI to test login):

> Account                              SubscriptionName           TenantId                             Environment      
> -------                              ----------------           --------                             -----------      
> *** {redacted} *** AzureUSGovernment
> 
> Name               : ADO_SPN
> Account            : ***
> Environment        : AzureUSGovernment
> Subscription       : 8580a5b7-{Redacted}
> Tenant             : ***
> TokenCache         : 
> VersionProfile     : 
> ExtendedProperties : {}

> WARNING: Switched active cloud to 'AzureUSGovernment'.

ADO log:

> Starting: Stop trigger(s) in DataFactory fdo-adf-MigTechnologies-MigDB-GlobalizeEventIdentifier-gcc-qat
==============================================================================
Task         : Azure Data Factory Trigger
Description  : Start/stop an Azure Data Factory Trigger
Version      : 2.5.1
Author       : Jan Pieter Posthuma
Help         : [More Information](https://github.com/liprec/vsts-publish-adf)
==============================================================================
##[error]Error login in to Azure. Please check the Service Configuration. Error: Get Token request returned http error: 400 and server response: {"error":"invalid_request","error_description":"AADSTS900382: Confidential Client is not supported in Cross Cloud request.\r\nTrace ID: 61ed79f2-{redacted}\r\nCorrelation ID: 84cff49e-{redacted}\r\nTimestamp: 2022-04-25 13:18:05Z","error_codes":[900382],"timestamp":"2022-04-25 13:18:05Z","trace_id":"61ed79f2-{redacted}","correlation_id":"84cff49e-{redacted}"}.
Finishing: Stop trigger(s) in DataFactory fdo-adf-MigTechnologies-MigDB-GlobalizeEventIdentifier-gcc-qat

**Comment by liprec** [comment] 2022-04-28 11:04
Thanks for the feedback and it looks like I missed something and will add a fix with the next release

**Comment by Sean-Steefel** [comment] 2022-04-28 16:33
FYI @liprec this failed also for the deploy option.. so it's not limited to the stop/start trigger task:
![image](https://user-images.githubusercontent.com/73724562/165800980-17a83d0e-3e5a-403c-b5a2-26a3326bc3f9.png)

**Comment by Sean-Steefel** [comment] 2022-05-03 14:35
@liprec Do you have a potential release date?

**Comment by liprec** [comment] 2022-05-05 06:17
Hi @Sean-Steefel,

Sorry for the late response, but somehow this bug slipped my mind: my target is to push an updated version this week.

-JP

**Comment by liprec** [comment] 2022-05-07 08:42
I just uploaded an updated version that should solve the login issue with sovereign clouds. Please let me know if it is working as expected as I cannot test it myself as I do not have access to anyone.

**Comment by liprec** [comment] 2022-05-26 05:53
@annapriyajose, can you make sure that the SP does have access to the resource group of the ADF? And can you make sure that the provided task options are without any typos?

But you can also share the logging of a run with a parameter `System.Debug` set to `true`, so I can take a better look.

**Comment by annapriyajose** [comment] 2022-05-26 14:47
@liprec Yes, the SPN has owner permission in ADF, and there is no typo and all as we are using the same task for deploying commercial ADFs which is working fine. And there wasn't much information about the error even on debugging, attaching the detailed log received on running the pipeline in 'Enable System diagnostics' option.
[ADF task debug logs.txt](https://github.com/liprec/vsts-publish-adf/files/8779797/ADF.task.debug.logs.txt)

**Comment by liprec** [comment] 2022-05-26 18:41
Can you make sure that the SPN has minimal `Reader` rights to the resource group?

**Comment by Sean-Steefel** [comment] 2022-05-27 03:01
Hi Jan - thanks for looking into this...  Yes the Service Principal is subscription owner - I verified that it has inherited ACL to the target resource group.

Sean Steefel
Cloud Architect

Valorem Reply
phone: +1 (816) 406-1688
mobile: +1 (918) 439-6363

**Comment by liprec** [comment] 2022-05-29 07:59
Is it possible to schedule an online meeting so I can look/test some things in the US Gov cloud? The problem is that I do not see what is causing the issue and I do not have access to any other cloud then the public one.

**Comment by annapriyajose** [comment] 2022-06-01 14:24
@liprec - Yes we can, let us know how and when you are free to have the meeting

**Comment by annapriyajose** [comment] 2022-06-02 07:54
@liprec , I have scheduled a meeting for today and send a meeting invite to your email 'mail@datascenarios.nl'. Feel free to reschedule if that time do not work for you.

**Comment by annapriyajose** [comment] 2022-06-09 09:25
@liprec , Confirmed that the issue is fixed now. Thank you for the support.

**Closed** 2022-06-14 18:52 UTC
Labels: bug
