### ISSUE TITLE
Issue with delete action

### ISSUE THREAD

**Issue by flo89bel** [liprec/vsts-publish-adf#57] opened 2020-05-13 08:54 UTC
Hi,

I just tried your delete action.
I dont fill it for linked services but the job deletes all items.

YAML :

```
steps:
- task: liprec.vsts-publish-adf.delete-adf-items.delete-adf-items@2
  displayName: 'Delete items from '
  inputs:
    azureSubscription: 'aaa'
    ResourceGroupName: 'bbb'
    DatafactoryName: ccc
    PipelineFilter: '*'
    DatasetFilter: '*'
    TriggerFilter: '*'
    Throttle: 1
```

Log :

```
2020-05-13T08:36:59.8124795Z Found 13 linked service(s).
2020-05-13T08:36:59.8126590Z Delete linked service 'LS_SQL'.
2020-05-13T08:37:00.6369964Z Delete linked service 'LS_SFDC'.
2020-05-13T08:37:00.9948543Z Delete linked service 'LS_KV_'.
2020-05-13T08:37:01.3383580Z ##[error]Error deleting 'LS_KV_' linked service : {"error":{"code":"BadRequest","message":"The document cannot be deleted since it is referenced by LS_ASQL_dusqlsrv_datacatalog.","target":"/Microsoft.DataFactory/factories/dudfqa01/linkedservices/LS_KV_","details":null}}
2020-05-13T08:37:01.3403222Z Delete linked service 'LS_FILE_'.
2020-05-13T08:37:01.3403740Z 13 linked service(s) deleted.
2020-05-13T08:37:01.3407453Z ##[error]Error deleting 'LS_KV_' linked service : {"error":{"code":"BadRequest","message":"The document cannot be deleted since it is referenced by LS_ASQL_.","target":"/Microsoft.DataFactory/factories/dudfqa01/linkedservices/LS_KV_","details":null}}
2020-05-13T08:37:02.1480163Z Delete linked service 'LS_FILE_'.
2020-05-13T08:37:03.3605479Z Delete linked service 'LS_FILE_'.
2020-05-13T08:37:03.3606066Z Delete linked service 'LS_DBR_'.
2020-05-13T08:37:03.6289694Z Delete linked service 'LS_DB2_'.
2020-05-13T08:37:04.3672617Z Delete linked service 'LS_ASQL_'.
2020-05-13T08:37:04.8071223Z Delete linked service 'LS_ASQL_'.
2020-05-13T08:37:05.2073642Z Delete linked service 'LS_ADLS_'.
2020-05-13T08:37:05.7605143Z Delete linked service 'LS_ADLS_'.
2020-05-13T08:37:06.0828130Z Delete linked service 'LS_ABLB_'.
```

Best regards,
Florian
---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=5faa75e7-bfc2-4ba0-a07f-6f06563724ca
* document_url=https://azurebi-docs.jppp.org/vsts-extensions/azure-data-factory-delete.html

**Comment by liprec** [comment] 2020-05-13 12:30
Closed as duplicate of #53

**Closed by liprec** 2020-05-13 12:30 UTC
Labels: bug, duplicate
