### ISSUE TITLE
toggle-adf-trigger@2 task to be deprecated

### ISSUE THREAD

**Issue by navjotsi** [liprec/vsts-publish-adf#77] opened 2021-11-29 07:15 UTC
Hi liprec, when using the task toggle adf trigger@2 to start/stop ADF triggers, I am getting this warning

This task uses Node 6 execution handler, which will be deprecated soon. If you are the developer of the task - please consider the migration guideline to Node 10 handler - https://aka.ms/migrateTaskNode10. If you are the user - feel free to reach out to the owners of this task

Can you assist\suggest what needs to be done here

**Comment by liprec** [comment] 2021-12-06 09:41
Duplicate of #76

**Closed by liprec** 2021-12-06 09:41 UTC
